### PR TITLE
Add amp-bind design doc

### PR DESCRIPTION
**Pull request by choumx**
/to @mrjoro /cc @cramforce

### CODE REVIEW

**Comment by mrjoro** [comment]
Can you add the license text to the top of the doc?

https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#weekly-design-reviews

**Comment by choumx** [comment]
@mrjoro Done. I couldn't copy the entire doc to my `ampproject.org` account since drawings fail to copy. Do you know of a better way to export/import docs from corp?

**Comment by mrjoro** [comment]
Since you're just exporting to PDF do you need to have it in your ampproject.org account?

I'm not sure of any great ways of exporting docs and importing them elsewhere.

**Comment by choumx** [comment]
No, but I noticed the other PDFs have open doc counterparts.

**Comment by cramforce** [comment]
@choumx The workflow I've been using:

- explicitly share google.com document with ampproject.org account.
- open with ampproject.org account and select to copy doc.
- share copy with everyone with the link

**Pull request merged**
